### ISSUE TITLE
make it compatible with Twitter Bootstrap js

### ISSUE THREAD

**Issue by raeesiqbal** [steelbrain/dQuery#36]

**Comment by steelbrain** [comment]
Something I have been planning for a long time

**Comment by steelbrain** [comment]
Things to do
- [ ] Set global `jQuery` variable to `$dQuery`
- [ ] Add a dummy `$dQuery.fn.jquery` version
- [ ] search parents if `dQuery.fn.closest` doesnt work for children
- [ ] Rename `$dQuery.event` to `$dQuery.Event`
- [ ] Support `$dQuery.fn.data` (even with no arguments)
- [ ] Alias `$dQuery.fn.matches` to `$dQuery.fn.is`
- [ ] Support $.proxy, maybe, alias for Function.prototype.bind
- [ ] Support `$dQuery.fn.prop` (El.X vs EL.getAttribute(X))
- [ ] Alias `$dQuery.fn.once` to `$dQuery.fn.one`
- [ ] Support multiple classes in {add, toggle, remove}Class
- [ ] Improve event namespacing
- [ ] Support `$dQuery.isFunction` <-- seriously?!
- [ ] Support `$dQuery.fn.detach`

**Comment by steelbrain** [comment]
No longer interested in maintaining this project
