### ISSUE TITLE
What is the lowest support version of IE?

### ISSUE THREAD

**Issue by BradHarris** [steelbrain/dQuery#40]

**Comment by steelbrain** [comment]
I don't really have any old internet explorer right now, but the one I have (Windows 10 Edge), all of the specs pass in it. 
Except for the .children one, because we are using a direct `:scope` css selector and IE doesn't support CSS3 selectors in querySelector

**Comment by baconface** [comment]
I have a subscription to Browser Stack. If you have a handful of tests you would want ran in IE I would be willing to give it ago when I got the chance.

**Comment by steelbrain** [comment]
The tests are in the specs folder, they are jasmine tests and I have tests for almost all of the methods.
