### ISSUE TITLE
how much of the sizzle selector engine is supported?

### ISSUE THREAD

**Issue by chovy** [steelbrain/dQuery#41]
Can this be a replacement for cheerio?

**Comment by steelbrain** [comment]
All of the css3 selectors are supported. If that's what you mean by it.

**Comment by anthonyettinger** [comment]
jquery has some more advanced selectors like `:visible` etc.

**Comment by steelbrain** [comment]
Well, selectors like that are not supported, :focus and others are supported. But I see your point, I'll try to implement those custom pseudo selectors soon (if they don't affect performance negatively).

**Comment by anthonyettinger** [comment]
can you implemenet sizzle?

**Comment by steelbrain** [comment]
Well, sizzle is only 4 kb, so I think I'll be doing it, yes.

**Comment by steelbrain** [comment]
No longer interested in maintaining this project
